# Problem 1

In [2]:
# 1 - numpy kütüphanesini import edin
import numpy as np
# 2 - 0 ile 10 arasında 5 sayıdan oluşan matris üretin
matris=np.random.randint(0,10,size=(5,))
# 3 - matris'in boyutunu öğrenin
boyut = matris.shape
# 4 - matris'i yeniden boyutlandırın
yeni=matris.reshape((5, 1))
# 5 - matris'in boyut sayısını öğrenin
bs=matris.ndim

# Problem 2

In [14]:
import numpy as np


#1 - 0 ile 10 arasında bulunan tek sayılardan oluşan matris üretin
matris = np.arange(1, 10, 2)
# 2 - Oluşturduğunuz matrisi parçalayın
parca1 = matris[:2]
parca2 = matris[2:]
# 3 - Parçalanmış matrisleri birleştirin
birlesik_matris = np.concatenate([parca1, parca2])
print("Oluşturulan matris:")
print(matris)

print("Parçalanan matrisler:")
print(parca1)
print(parca2)

print("Birleştirilmiş matris:")
print(birlesik_matris)


Oluşturulan matris:
[1 3 5 7 9]
Parçalanan matrisler:
[1 3]
[5 7 9]
Birleştirilmiş matris:
[1 3 5 7 9]


# Problem 3

In [15]:
import numpy as np
# 1 - 5 ile 100 arasında ikişer ikişer atlayarak rastgele 10 sayıdan oluşan matris üretin
m=np.random.choice(np.arange(5, 101, 2),size=(10,))
# 2 - matris'in özelliklerini inceleyin
boyut = matris.shape
boyut_sayisi= matris.ndim
eleman_sayisi= matris.size
minimum_deger= matris.min()
maksimum_deger= matris.max()
ortalama_deger= matris.mean()